name: Putative lineage proposal
description: Use this template to suggest a new lineage
title: "[NEW LINEAGE PROPOSAL]: "
labels: ["lineage proposal"]
body:
  - type: markdown
    attributes: 
      value: Thanks for taking the time to propose a new lineage! Please read instructions [here](https://denv-lineages.github.io/_pages/rules/) before suggesting a lineage

  - type: checkboxes
    id: mutations
    attributes:
      label: is it phylogentically distinct enough?
      options:
      - label: There are at least *20* inferred substitutions along the preceding branch for minor lineages or 25 for major
        required: false

  - type: checkboxes
    id: size
    attributes:
      label: is it big enough?
      options:
      - label: There are at least 15 sequences in the clade
        required: false

  - type: checkboxes
    id: sister
    attributes:
      label: is there a sister lineage?
      options:
      - label: There is at least one other lineage meeting size/distance criteria at the same level of designation
        required: false

  - type: textarea
    id: evidence
    attributes:
      label: Evidence of rules
      description: Please provide number of mutations on branch leading up to clade, number of sequences in clade, and picture of phylogenetic area containing sister lineage
    validations:
      required: true


  - type: dropdown
    id: serotype
    attributes:
      label: What serotype is it part of?
      multiple: true
      options:
      - DENV1
      - DENV2
      - DENV3
      - DENV4
    validations:
     required: true

  - type: dropdown
    id: genotype
    attributes:
      label: What genotype is it a part of?
      multiple: true
      options:
        - 1I
        - 1II
        - 1III
        - 1IV
        - 1V
        - 1VI
        - 1VII
        - 2I
        - 2II
        - 2III
        - 2IV
        - 2V
        - 2VI
        - 3I
        - 3II
        - 3III
        - 3IV
        - 3V
        - 4I
        - 4II
        - 4III
        - 4IV

  - type: dropdown
    id: maj-min
    attributes:
      label: Are you prosing a major lineage or a minor lineage?
      multiple: true
      options:
        - major
        - minor

  - type: checkboxes
    id: name-check
    attributes:
      label: Is the name currently available?
      options:
      - label: I have checked the available putative names
        required: true

  - type: textarea
    id: lineage-name
    attributes:
      label: Suggested name of the lineage
      description: suggested name of the lineage 
    validations:
      required: false

  - type: textarea
    id: tip-names
    attributes:
      label: Accession IDs of sequences in the lineage
      description: please provide *genbank* IDs for the the sequences the clade. Due to difficulties with matching Genbank and GISAID IDs and the presence of duplicates, we will not use gisaid IDs to designate lineages 

  - type: textarea
    id: lineage-description
    attributes:
      label: Description of the lineage
      description: Anything else you want us to know about the lineage? (optional)
    validations:
      required: false
